### ISSUE TITLE
Magic calculated incorrectly

### ISSUE THREAD

**Issue by lordblades** [chummer5a/chummer5a#2312]
### Environment
Chummer Version: 5.196.45
Environment: Windows 7 SP1
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Magic should be 3. Character has started with 2 Magic (priority D Adept), has bought cyberware reducing his magic to 0 (and maximum magic to 1), then has purchased initiations and magic until Magic 3 (Still visible in 'Karma and Nuyen' tab). 

### Actual behaviour
Magic is calculated as 0 (maximum Magic is correct). This was working in older versions (When character was created).

### Steps to reproduce the behaviour
Unsure how to reproduce, as character was working fine before

### Link to affected character file

[Spikes Troll.zip](https://github.com/chummer5a/chummer5a/files/1632514/Spikes.Troll.zip)

**Comment by DelnarErsike** [comment]
This is an issue related to the way "burning out" is handled. Currently, "burning out" is handled as a modifier through the improvement system, but the problem is that there's no way to properly make it work that way for karma values (past versions had different problems, mainly related to increasing MAG with karma first and then burning out).

**Comment by chummer5a** [comment]
What are we gaining by allowing minimum to dip below zero, though?

**Comment by DelnarErsike** [comment]
Accuracy spending special attribute points are spent on a special attribute that has been burned one more time after it has been burned enough to drop the minimum to 0.

**Comment by lordblades** [comment]
Based on what you guys are discussing, I assume the way for me to fix this character for now is to just add an Improvement for enough Magic to reach the correct total, right?

**Comment by DelnarErsike** [comment]
That'd be a patchwork fix.

The core issue is with the following bit of code:

`public int Value
        {
            get
            {
                return Math.Min(Math.Max(Base + FreeBase + RawMinimum + CareerKarma + AttributeValueModifiers, TotalMinimum) + CreateKarma, TotalMaximum);
            }
        }`

Previously, this was:

`public int Value
        {
            get
            {
                return Math.Min(Math.Max(Base + FreeBase + TotalMinimum + CareerKarma + CreateKarma + AttributeValueModifiers, TotalMinimum), TotalMaximum);
            }
        }`

The main difference between `TotalMinimum` and `RawMinimum` is that `TotalMinimum` does not allow the returned value to drop below 0, while `RawMinimum` does not care (Essence Loss currently modifies your current value by lowering your minimum instead of taking away levels the way it's supposed to by RAW). For example, if you chose Adept D and then dropped to 3.00 Essence, `RawMinimum` of your MAG would be -1 (since 2-3=-1) while `TotalMinimum` of your MAG would be 0.

**Comment by DelnarErsike** [comment]
I added a (slightly hacky) fix to the issue, but it needs testing to make sure it works properly. Short version: whenever the reduction in special attributes is increased in career mode, the system should burn away karma levels if possible before reducing the metatype minimum, and Value is now calculated with all Karma levels (not just chargen ones) outside of the RawMinimum/TotalMinimum section.

This needs testing because of the many wonky ways one can end up burning special attributes through Essence loss, so I'm assigning the "response pending" tag to this issue and will wait a couple days for further feedback before closing it.

**Comment by lordblades** [comment]
I gave it a try just now in Chummer 5.197. My old character still behaves the same (shows 0 magic) and I tried a new character (human, with metatype A and Magic D as Adept with 2 Magic): Added some cyberware in creation mode ( about 4.5 essence worth of stuff), special attributes behaved as expected (first 3 went into the 'hole', only  from 4 onward did Magic increase). I then saved it as created (tried twice, first time with 0 Magic/1 max Magic, second time with 1 and 1). The Magic stat was gone both times, as for a mundane character.

**Comment by DelnarErsike** [comment]
Yeah, I know it's bugged in the currently nightly, as I forgot to properly remove create-mode-essence-loss modifiers when calculating career-mode ones (and I need to calculate the latter separately so that I can properly burn away career karma instead of modifying minima). See where it's still buggy with the next nightly.

**Comment by DelnarErsike** [comment]
Yeah, there is an issue with improvements for essence loss not getting committed after they were created up to 5.197.6. It should be fixed by 5.197.7, so give it a try then and see if you're still getting issues.

**Comment by lordblades** [comment]
Just tested it in 5.197.7. My existing character is still broken (the moment I remove the custom improvement for magic it drops back to magic 0). Any idea if a fix for existing characters is possible? The behavior for new characters is (almost right). Did the same as above (human, with metatype A and Magic D as Adept with 2 Magic, add cyberware in create mode until magic drops below 0, 4.5 essence for 2 magic character). The behavior of special attributes is normal (first few go into the 'hole', then magic increases as normal), however, upon saving the character I noticed the following: If the character exists creation with at least 1 magic remaining everything works out normal (yay :D ). However, if the character exists creation with magic 0, it becomes mundane (Magic is gone completely);

**Comment by DelnarErsike** [comment]
Got that burning out thing fixed in the latest commit. It was due to me working off of attribute value differences instead of attribute maxima differences when it came to determining how much of a maximum modifier needs to be applied to characters' special attributes.

Existing characters that were saved while the original, karma-level-draining bug was up will need to have their savefiles edited manually if you want to recover the lost karma levels. Open up the `.chum5` file in a text editor like Notepad++, go down to the `<attributes>` section, look for the entry for your desired special attribute (ignore MAGAdept in almost all cases, I'll get to the cases where you'll need to worry about that, too), and then change the numbers next to `<base>`, `<karma>`, and `<metatypemin>` until the total amount of spent levels matches those of the original character. `<base>` is the total amount of special attribute points spent, `<karma>` is the total amount of levels gained with karma, `<metatypemin>` would be the value of the attribute from your priority (or 1 if you're using karma-based generation). If `<metatypemax>` and `<metatypeaugmax>` are something unexpected (they both control the maximum for the attribute), change those, too. If the character got completely burned out from the bug, you'll need to look for `<magenabled>` or `<resenabled>` in the savefile and set the appropriate one's value to `True`. If you're a Mystic Adept who lost PPs gained at character creation, you'll need to modify `<magsplitadept>` and set its value to however many PPs you should have. If you're a Mystic Adept and you're using the "Mystic Adepts get a 2nd Magic Attribute instead of their weird PP system" houserule, that's when you'll need to address MAGAdept in addition to MAG (MAGAdept is the adept-specific MAG, MAG is the magician-specific MAG).

**Comment by lordblades** [comment]
Tried doing as instructed above in 5.197.8. My relevant stat block (Troll Adept, Priority D Magic, 3 Magic bought with Karma) looks like this now:

<attribute>
      <name>MAG</name>
      <metatypemin>2</metatypemin>
      <metatypemax>6</metatypemax>
      <metatypeaugmax>6</metatypeaugmax>
      <base>0</base>
      <karma>3</karma>
      <augmodifier>0</augmodifier>
      <metatypecategory>Standard</metatypecategory>
      <totalvalue>3</totalvalue>
    </attribute>


In Chummer however I'm still getting Magic 0. Moreover, if I save the character, <karma> and <totalvalue> get overwritten to 0. 
[Spikes Troll.zip](https://github.com/chummer5a/chummer5a/files/1657639/Spikes.Troll.zip)

I'm also getting another weird glitch: even though I deleted my 3 Magic improvement, I'm getting an augmented value for Magic in brackets (My Magic shows up as 0(0) instead of 0). Also attaching the char file, maybe I'm missing something.

[Spikes Troll.zip](https://github.com/chummer5a/chummer5a/files/1657639/Spikes.Troll.zip)

**Comment by DelnarErsike** [comment]
You're not missing anything, there was just a bug left in the code that I wasn't aware of yet (short version: MAG karma got burned twice for most characters). The fix will be in the next nightly.

**Comment by lordblades** [comment]
Just retested it in 5.197.11 and it's till behaving the same (Magic still appears as 0(0) ).

**Comment by DelnarErsike** [comment]
As is, it's working as intended. They're losing 5 MAG to essence loss, and they have 2 priority-bought MAG levels and 3 karma-bought ones (Chummer5 can't distinguish between essence loss that occurred before or after karma levels are bought if you're loading from a character who was set up before the system that can distinguish was put in place). 5 - 5 = 0. Notice how if you delete Narco from the savefile, which causes them to only lose 4 MAG from essence loss in total, their MAG becomes 1.

**Comment by lordblades** [comment]
Thanks for clarifying. I managed to fix the character by simply adding more to the Karma line of magic. if I put 6 then it seems to work correctly (3 magic) until I try to increase it again. In any case, I made it work for this character.

Before that however, I tried rebuilding it from scratch and I discovered it's still buggy. I built the troll, put into career mode with 2 magic. Added all the 'ware back (1.83 ess left), magic dropped to 0 as expected. I tried to increase it to 1, I paid the 5 karma, but magic immediately went back to 0. Managed to do that 5-6 times, until chummer crashed.

**Comment by DelnarErsike** [comment]
Bah, I knew that approach would bite me in the ass somehow. Latest commit changes the logic behind how Chummer5 calculates what gets burned. It should both fix the issue of magic levels getting burned and hopefully not generate its own issues... I'm not holding my breath, though.

**Comment by lordblades** [comment]
Everything seems to be working properly now.

**Comment by DelnarErsike** [comment]
Good to hear. I'm closing the issue then, but please feel free to re-open it if you encounter any unusual behavior regarding essence loss in career mode in the future.
