### ISSUE TITLE
Crashing - Advanced Lifestyles

### ISSUE THREAD

**Issue by Mr-J** [chummer5a/chummer5a#2362]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.197.1.0
Environment: Windows 10
Runtime: .NET Framework 4.7.1

### Expected behaviour
1. Applying "Trust Fund" Option should set Cost to 0.
2. Adding Qualities should open menu to add qualities

### Actual behaviour
1. Cost set to zero only displayed, costs still applied (for example High Lifestyle with Trust Fund still cost 10.000).
2. Program crashes

### Steps to reproduce the behaviour
1. Create new Charakter
2. Add negative Quality SIN-ner
3. Add positive Quality Trust Fund III
4. Add Advanced Lifestyle -> High Lifestyle with "Trust fund" option applied
-> Costs for Lifestyle deducted from initial funds
---
5. Select "Add quality" in Advanced Lifestyle
-> Program crashes

### Link to affected character file
Crashlogs are empty, example added 

[chummer_crash_131609632295091520.txt](https://github.com/chummer5a/chummer5a/files/1649382/chummer_crash_131609632295091520.txt)

Added affected character file

[Mr. J.zip](https://github.com/chummer5a/chummer5a/files/1649384/Mr.J.zip)

**Comment by DelnarErsike** [comment]
Can't replicate the crash when adding a quality to an advanced lifestyle.

The costs issue should be fixed with the latest commit, so it should be present in the next nightly.

**Comment by Mr-J** [comment]
Crashing started when i switched from Win7 to Win10. Is there an option to completely reset Chummer5, maybe there is some wrong option setting. Already tried to delete chummer and redownload a fresh copy but didn't work. I also noticed that the message which books i want to use only appeared on first install and not on the reinstallations.

**Comment by DelnarErsike** [comment]
You can completely reset Chummer by deleting its keys in HKEY_CURRENT_USER > Software > Chummer5, and then deleting Chummer5a and downloading a fresh copy.

**Comment by Mr-J** [comment]
Resetting didn't change behaviour, still crashing.
Switching Back to Version 5.196.0 works, program not crashing. 

The only difference between version i noted was the different ordering of the tabs in "Street Gear", old version has "Lifestyle" tab first and new version has it at last position, maybe there is some error?

Error occurs when trying to add a new quality to a new or existing advanced lifestyle. There is no problem removing qualities from existing lifestyle, so i assume there is some problem for the programm to open the option list for the advanced lifestyles.

**Comment by chummer5a** [comment]
Can you try with the latest nightly build? If nothing else, the crash handler will properly export the exception info.
