### ISSUE TITLE
Nightly Build Fails to Apply Essence Cost Discounts

### ISSUE THREAD

**Issue by LeonardoDeQuirm** [chummer5a/chummer5a#3585]
**Describe the bug**
After updating to the newest nightly build (5.205.40), the program fails to calculate Essence discounts on my cyberware correctly. The attached character should have 0.78 Essence, but with the incorrect math, he's reduced to -0.37. If I attempt the Reapply Improvements, the program freezes.

**To Reproduce**
1. Load a character with cyberware and effects that reduce Essence cost, that was created with a prior version
2. On the Augmentation tab, observe the lack of discounts applied.
3. Select Special ->Reapply Improvements

**Expected behavior**
Effects such as Biocompatability and Adapsin should 

**Screenshots**
Not needed

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

[Baldur.txt](https://github.com/chummer5a/chummer5a/files/3086207/Baldur.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.18362 Build 18362

**Comment by chummer5a** [comment]
[Baldur_Fixed.txt](https://github.com/chummer5a/chummer5a/files/3087964/Baldur_Fixed.txt)
Should be fixed; the multiplier for your essence wasn't being stored properly. I have a vague suspicion it might continue to not save/load properly, but it should behave. Please test and let me know if anything changes.

**Comment by LeonardoDeQuirm** [comment]
With testing, the file can be saved and loaded, however trying to reapply improvements still causes a crash. In addition, while the modification you made to adjust for Biocompatability is right, it's still not doing the math for Adapsin. The following is a PDF version with the right essence costs recorded from a previous working version if you wanted to check.
[Baldur.pdf](https://github.com/chummer5a/chummer5a/files/3090718/Baldur.pdf)

**Comment by chummer5a** [comment]
I think this is resolved in the current nightly builds, can you confirm?
